name: Build project

on: [push, workflow_dispatch]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    defaults:
      run:
        working-directory: ./TakeApp
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Restore cache
        run: |
          unpack.cmd takeapp
      - name: Unity Build (windows native)
        run: |
          unity.cmd takeapp.build.method
      - name: Fill cache
        run: |
          pack.cmd takeapp
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: Builds/*.apk
