on: [workflow_dispatch]

jobs:
  slack_upload_job:
    runs-on: windows-latest
    name: Upload test file(s)
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upload to slack
        uses: MeilCli/slack-upload-file@v2
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: cicd-test
          file_path: './Packages/*.json'
          file_type: 'auto'
          initial_comment: 'post by slack-upload-file'
          
